version: '3.9'

services:
  kowl:
    build:
      context: ./kowl
    container_name: kowl
    hostname: kowl
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ${PWD}/kowl/config.yaml:/app/config.yaml:ro
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda
    hostname: redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:29092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:8082,OUTSIDE://0.0.0.0:28082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:8082,OUTSIDE://localhost:82082
  producer:
    hostname: producer
    deploy:
      replicas: 50
    build:
      context: ./producer
    restart: always
    environment:
      - BOOTSTRAP_SERVERS=redpanda:9092,
      - TOPIC_NAME=filebeat
      - INIT_DELAY=0
      - BATCH_SIZE=16384
      - LINGER_MS=0
      - COMPRESSION=gzip
      - MESSAGE_SIZE=1024
      - GROUP_NAME="seemscloud"
      - PROMETHEUS_MULTIPROC_DIR=/tmp/
      - LOG_LEVEL=INFO
  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always